import type { SnapshotRow } from "./storage";
import { computeHeat } from "./heat";
import { classify } from "./classify";

export type DigestData = {
  capturedAt: string;
  daily: SnapshotRow[];
  weekly: SnapshotRow[];
  monthly: SnapshotRow[];
  movers?: {
    risers: { owner: string; repo: string; from: number; to: number }[];
    fallers: { owner: string; repo: string; from: number; to: number }[];
    newEntries: { owner: string; repo: string; rank: number }[];
  };
};

export function generateMarkdownDigest(data: DigestData): string {
  const lines: string[] = [];

  lines.push(`# GitHub Trending Digest — ${data.capturedAt}`);
  lines.push("");

  const sections: { title: string; rows: SnapshotRow[]; tag: string }[] = [
    { title: "🔥 Top hôm nay (Daily)", rows: data.daily, tag: "today" },
    { title: "📅 Top tuần này (Weekly)", rows: data.weekly, tag: "week" },
    { title: "📆 Top tháng này (Monthly)", rows: data.monthly, tag: "month" },
  ];

  for (const sec of sections) {
    lines.push(`## ${sec.title}`);
    lines.push("");
    if (sec.rows.length === 0) {
      lines.push("_No data._");
      lines.push("");
      continue;
    }
    for (const r of sec.rows.slice(0, 10)) {
      const heat = computeHeat({
        starsGained: r.stars_gained,
        totalStars: r.total_stars,
        rank: r.rank,
      });
      const cls = classify({
        starsGained: r.stars_gained,
        totalStars: r.total_stars,
        language: r.language,
      });
      const lang = r.language ?? "—";
      const gained =
        r.stars_gained != null ? `+${r.stars_gained.toLocaleString()}` : "?";
      const total =
        r.total_stars != null ? r.total_stars.toLocaleString() : "?";
      lines.push(
        `${r.rank}. **[${r.owner}/${r.repo}](${r.url})** — \`${lang}\` · ${gained} ★ today · ${total} total · heat \`${heat}\` · _${cls}_`,
      );
      if (r.description) {
        lines.push(`   > ${r.description.slice(0, 200)}`);
      }
    }
    lines.push("");
  }

  if (data.movers) {
    lines.push("## 📊 Movers vs hôm qua");
    lines.push("");

    if (data.movers.risers.length) {
      lines.push("### ▲ Risers");
      for (const m of data.movers.risers.slice(0, 5)) {
        lines.push(`- **${m.owner}/${m.repo}**: #${m.from} → #${m.to}`);
      }
      lines.push("");
    }

    if (data.movers.newEntries.length) {
      lines.push("### 🆕 New entries");
      for (const m of data.movers.newEntries.slice(0, 5)) {
        lines.push(`- **${m.owner}/${m.repo}** at #${m.rank}`);
      }
      lines.push("");
    }

    if (data.movers.fallers.length) {
      lines.push("### ▼ Fallers");
      for (const m of data.movers.fallers.slice(0, 5)) {
        lines.push(`- **${m.owner}/${m.repo}**: #${m.from} → #${m.to}`);
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("");
  lines.push("_Generated by Agent Radar — github.com/trending snapshot_");
  return lines.join("\n");
}
